__author__ = "Paul Council, Joseph Gonzoph, Anand Patel"
__version__ = "sprint2"

# imports
import time

from ClientPackage.PlayerClient import *
from AvailablePlayers.TestPlayer1 import *


my_player = TestPlayer1()
client = PlayerClient(my_player)
# attempt to connect player to server
client.client_connect(host="150.250.190.253")

# verify connection
client.verify_connection()

# attempt to register this player in the tournament
client.register_player()

# request a verification that this player has been registered to the tournament
client.verify_registration()
time.sleep(10)

# submit move to server for match that should have been generated by GameController by now...

client.submit_move()

time.sleep(10)

client.get_round_results()

# close the connection
client.close_connection()
